<a href="https://colab.research.google.com/github/ariadnemnp/ariadnemnp/blob/main/Deposit_Trend_Indonesia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📊 Deposit Trends and the Changing Financial Habits of Indonesians

The dataset used for this analysis is from Indonesian Financial and Economic Statistics, covering deposits in commercial and rural banks from 2010 to 2024.One data wrangling i did was to convert data type: year to object and other data to integer.

It is shown that deposit amount consistently increase in line with the number of accounts, indicating growing financial engagement in Indonesia.

What does this trend say about financial habit of Indonesian people? Next, I’ll explore whether people prefer to save in short-term or long-term instrument.

## Part 1 — Find a Dataset (Upload)

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [9]:
data = '/content/drive/MyDrive/Colab Notebooks/Rev Banking Data Indonesia.csv'

## Part 2 — Load & Inspect

In [10]:
import pandas as pd

df = pd.read_csv(data)
rows, cols = df.shape
rows, cols

(15, 13)

In [11]:
df.head(15)

,Year,Total Deposit,Demand Deposit,Saving Deposit,Time Deposit,1 Month Time Deposit,3 Month Time Deposit,6 Month Time Deposit,12 Month Time Deposit,24 Month Time Deposit,Others,Matured Deposits,Number of Account
0,2010,"2,304,875","504,096","738,695","1,062,084","542,497","323,790","91,176","93,488","1,609","8,822",702,"97,204,863"
1,2011,"2,736,415","605,085","905,700","1,225,630","609,109","373,948","123,882","94,166","5,497","18,351",677,"101,503,564"
2,2012,"3,163,519","710,400","1,085,743","1,367,377","596,108","425,804","170,200","153,227","3,137","18,616",285,"119,917,930"
3,2013,"3,578,208","797,243","1,222,029","1,558,935","758,313","428,975","188,930","132,338","30,286","15,101","4,991","147,626,510"
4,2014,"4,013,817","845,667","1,298,326","1,869,823","921,542","497,681","203,592","175,828","44,023","26,440",717,"160,881,757"
5,2015,"4,335,269","937,089","1,411,620","1,986,560","883,859","626,063","227,586","155,825","49,202","41,151","2,875","175,994,476"
6,2016,"4,749,400","1,065,072","1,569,943","2,114,385","958,102","570,157","240,312","200,813","45,070","28,828","71,103","199,301,222"
7,2017,"5,142,991","1,153,733","1,720,959","2,268,299","942,449","666,230","292,500","194,294","57,619","32,252","82,954","242,396,164"
8,2018,"5,457,228","1,213,887","1,847,928","2,395,414","1,016,271","737,593","269,701","165,002","37,295","26,402","143,151","275,764,037"
9,2019,"5,805,078","1,351,901","1,968,855","2,484,323","967,214","794,936","289,853","196,029","63,535","28,107","144,648","301,697,958"
10,2020,"6,465,103","1,580,036","2,196,025","2,689,041","1,122,427","844,443","290,833","201,258","46,010","30,141","153,928","350,324,950"
11,2021,"7,253,263","2,006,916","2,454,070","2,792,277","1,124,485","782,676","317,935","297,368","56,457","34,550","178,806","386,319,094"
12,2022,"7,932,190","2,429,991","2,637,474","2,864,725","1,345,756","717,528","283,170","289,237","27,126","34,411","167,497","508,546,341"
13,2023,"8,235,948","2,524,880","2,691,261","3,019,807","1,197,511","905,180","365,670","330,102","10,784","32,234","178,324","559,914,590"
14,2024,"8,572,650","2,579,530","2,868,611","3,124,509","1,155,383","1,066,480","438,111","240,173","8,672","26,555","189,135","609,218,193"

## Part 3 — Explore & Clean

In [12]:
df.dtypes

Year                      int64
Total Deposit            object
Demand Deposit           object
Saving Deposit           object
Time Deposit             object
1 Month Time Deposit     object
3 Month Time Deposit     object
6 Month Time Deposit     object
12 Month Time Deposit    object
24 Month Time Deposit    object
Others                   object
Matured Deposits         object
Number of Account        object
dtype: object

In [18]:

    df = pd.read_csv(data)

    cols_to_convert = [
        'Total Deposit', 'Demand Deposit', 'Saving Deposit', 'Time Deposit',
        '1 Month Time Deposit', '3 Month Time Deposit', '6 Month Time Deposit',
        '12 Month Time Deposit', '24 Month Time Deposit', 'Others',
        'Matured Deposits', 'Number of Account'
    ]

    for col in cols_to_convert:
        # Step 1: Remove commas and spaces
        df[col] = df[col].str.replace(',', '').str.strip()

        # Step 2: Convert to numeric (float), coerce errors to NaN
        df[col] = pd.to_numeric(df[col], errors='coerce')

        # Step 3: If there are no NaNs, convert to integer
        if df[col].isnull().sum() == 0:
            df[col] = df[col].astype(int)
        else:
            print(f"⚠️ Column '{col}' contains missing values; kept as float.")

    df['Year'] = df['Year'].astype(str)

In [19]:
df.dtypes

Year                     object
Total Deposit             int64
Demand Deposit            int64
Saving Deposit            int64
Time Deposit              int64
1 Month Time Deposit      int64
3 Month Time Deposit      int64
6 Month Time Deposit      int64
12 Month Time Deposit     int64
24 Month Time Deposit     int64
Others                    int64
Matured Deposits          int64
Number of Account         int64
dtype: object

In [21]:
df.isnull().sum().sort_values(ascending=False).head(10)

Year                     0
Total Deposit            0
Demand Deposit           0
Saving Deposit           0
Time Deposit             0
1 Month Time Deposit     0
3 Month Time Deposit     0
6 Month Time Deposit     0
12 Month Time Deposit    0
24 Month Time Deposit    0
dtype: int64

## Part 4 — Summarization

In [23]:
category_col = 'Year'
numeric_cols = ['Demand Deposit', 'Saving Deposit', 'Time Deposit']

by_cat = df.groupby(category_col)[numeric_cols].sum().sort_values(by=numeric_cols, ascending=False)
by_cat.head(10)

      Demand Deposit  Saving Deposit  Time Deposit
Year
2024         2579530         2868611       3124509
2023         2524880         2691261       3019807
2022         2429991         2637474       2864725
2021         2006916         2454070       2792277
2020         1580036         2196025       2689041
2019         1351901         1968855       2484323
2018         1213887         1847928       2395414
2017         1153733         1720959       2268299
2016         1065072         1569943       2114385
2015          937089         1411620       1986560

## Part 5 — Visualization (Pandas + Plotly)

In [24]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

fig = make_subplots()
fig.add_trace(go.Scatter(x=df['Year'], y=df['Number of Account'], name='Number of Account', mode="lines"))
fig.show()

In [25]:
fig = make_subplots(specs=[[{"secondary_y": True}]])
fig.add_trace(
    go.Scatter(x=df['Year'], y=df['Number of Account'], name='Number of Account', mode="lines"),
    secondary_y=True,
)

fig.add_trace(
    go.Bar(x=df['Year'], y=df['Total Deposit'], name='Total Deposit'),
    secondary_y=False,
)

fig.update_layout(title_text="Number of Accounts and Total Deposit Over Time")
fig.update_xaxes(title_text="Year")
fig.update_yaxes(title_text="Total Deposit", secondary_y=False)
fig.update_yaxes(title_text="Number of Account", secondary_y=True)

fig.show()

In [ ]:
import plotly.express as px

bar_df = by_cat.head(10).reset_index()
fig = px.bar(bar_df, x=category_col, y=numeric_col, title=f'Top 10 {category_col} (interactive)')
fig.show()

## Part 6 — Reflection
- What needed adjusting when you switched datasets?
- What was easier/harder vs the workbook?
- What context/limitations should a policymaker know?

## Part 7 — ⚡ Lightning Chart Demos — Teach-Out Instructions

### What is a Lightning Demo?
A **rapid-fire mini-presentation**: 2 minutes per group. Show **one chart** + **one insight**, not your whole notebook.

### Demo Format (2 minutes)
1. **Context (15 sec):** Dataset name + 1-sentence purpose.  
2. **Chart + Insight (75–90 sec):** Show interactive Plotly chart; state one clear finding; name one wrangling step.  
3. **Caveat or Next Step (15–30 sec):** One limitation OR next idea.  
4. **Pass the mic (10 sec):** End with *“Any questions about our chart?”*

### Unique Angles
- Aggregation choice (sum vs mean, raw vs normalized).  
- Data cleaning step (conversion, deduping).  
- Encoding (bar vs line vs scatter).  
- Interactivity (facet, hover, filter).  
- Comparability (per capita vs raw counts).  
- Temporal nuance (trend vs snapshot).  

👉 If another group showed your angle, pick a different one.

### Flow for the Day
- Groups present **clustered by chart type** (bars, lines, scatter, other).  
- Instructor summarizes similarities/differences after each cluster.  
- 15 groups × 2 min = ~30 minutes + transitions = ~40 minutes.

### Presenter Checklist
- [ ] Dataset URL loads in Colab  
- [ ] Columns chosen make sense  
- [ ] One **interactive Plotly figure** with title + labels  
- [ ] Insight stated in one sentence  
- [ ] One cleaning step mentioned  

### Audience Task
After each cluster, jot 1 sentence:  
- What was **similar** across charts?  
- What was **different** (aggregation, encoding, interactivity)?  
- Which chart best supported a **policy decision**—and why?

---
### Quick Rubric (3 pts)
- **Clarity of claim (1 pt)**  
- **Method fit (1 pt)**  
- **Insight/caveat (1 pt)**  
(Bonus +0.5 for meaningful interactivity)

---
### Minimal Code Patterns

**Top-N bar:**
```python
bar_df = df.groupby(category_col)[numeric_col].sum().nlargest(10).reset_index()
fig = px.bar(bar_df, x=category_col, y=numeric_col,
             title=f"Top 10 {category_col} by {numeric_col}")
fig.show()
```

**Time series:**
```python
ts = (df.groupby(time_col)[numeric_col]
        .sum()
        .reset_index()
        .sort_values(time_col))
fig = px.line(ts, x=time_col, y=numeric_col, markers=True,
              title=f"{numeric_col} over time")
fig.show()
```

**Scatter:**
```python
fig = px.scatter(df, x=x_col, y=y_col, trendline="ols",
                 title=f"{y_col} vs {x_col}")
fig.show()
```

---

In [ ]:
csv_url = "PASTE-RAW-CSV-URL-HERE"
csv_url